# Generated by Django 4.2.7 on 2025-12-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whiteboard',
            options={'ordering': ['-created_at']},
        ),
    ]
