# Generated by Django 4.2.7 on 2025-11-26 16:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('rectangle', 'Rectangle'), ('circle', 'Circle'), ('triangle', 'Triangle'), ('line', 'Line'), ('arrow', 'Arrow'), ('freehand', 'Freehand'), ('text', 'Text'), ('sticky_note', 'Sticky Note'), ('image', 'Image')], max_length=20)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('stroke_width', models.IntegerField(default=2)),
                ('z_index', models.IntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.IntegerField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('whiteboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_objects', to='boards.whiteboard')),
            ],
            options={
                'ordering': ['z_index', 'created_at'],
            },
        ),
    ]
